# Generated by Django 2.0.6 on 2018-06-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='c1T100',
            field=models.IntegerField(verbose_name='65℃湯種鮮奶吐司'),
        ),
        migrations.AlterField(
            model_name='order',
            name='c1T120',
            field=models.IntegerField(verbose_name='65℃湯種鮮奶葡萄乾吐司'),
        ),
        migrations.AlterField(
            model_name='order',
            name='c1T130',
            field=models.IntegerField(verbose_name='65℃湯種鮮奶蔓越莓吐司'),
        ),
        migrations.AlterField(
            model_name='order',
            name='c1T140',
            field=models.IntegerField(verbose_name='65℃湯種鮮奶核桃吐司'),
        ),
        migrations.AlterField(
            model_name='order',
            name='c1T150',
            field=models.IntegerField(verbose_name='65℃湯種鮮奶堅果吐司'),
        ),
        migrations.AlterField(
            model_name='order',
            name='c2T100',
            field=models.IntegerField(verbose_name='健康全粒粉吐司'),
        ),
        migrations.AlterField(
            model_name='order',
            name='c2T120',
            field=models.IntegerField(verbose_name='健康全粒粉葡萄乾吐司'),
        ),
        migrations.AlterField(
            model_name='order',
            name='c2T130',
            field=models.IntegerField(verbose_name='健康全粒粉蔓越莓吐司'),
        ),
        migrations.AlterField(
            model_name='order',
            name='c2T140',
            field=models.IntegerField(verbose_name='健康全粒粉核桃吐司'),
        ),
        migrations.AlterField(
            model_name='order',
            name='c2T150',
            field=models.IntegerField(verbose_name='健康全粒粉堅果吐司'),
        ),
        migrations.AlterField(
            model_name='order',
            name='c3M50',
            field=models.IntegerField(verbose_name='超厚健康酵母鬆餅'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cDate',
            field=models.DateField(verbose_name='取貨日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cName',
            field=models.CharField(max_length=20, verbose_name='訂購者'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cPhone',
            field=models.CharField(max_length=10, verbose_name='聯絡電話'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cSpot',
            field=models.CharField(default='自取', max_length=20, verbose_name='取貨地點'),
        ),
    ]
