# Generated by Django 2.0.6 on 2018-06-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0002_auto_20180609_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='c3M50',
            new_name='c2M50',
        ),
        migrations.RemoveField(
            model_name='order',
            name='c1T150',
        ),
        migrations.RemoveField(
            model_name='order',
            name='c2T100',
        ),
        migrations.RemoveField(
            model_name='order',
            name='c2T120',
        ),
        migrations.RemoveField(
            model_name='order',
            name='c2T130',
        ),
        migrations.RemoveField(
            model_name='order',
            name='c2T140',
        ),
        migrations.RemoveField(
            model_name='order',
            name='c2T150',
        ),
    ]
