# Generated by Django 2.0.6 on 2018-06-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0004_auto_20180610_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='c2M50_thickless',
        ),
    ]
